name: SwiftLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: norio-nomura/action-swiftlint@3.2.1
